/**
 * Textos y copys centralizados de la feature de administración (PR106-H16).
 */
export const ADMIN_COPY = {
  nav: {
    brandLabel: 'Panel de Administración cadeApp',
    badgeText: 'Admin (Aguilares)',
    logoutButton: 'Salir',
    ariaLabel: 'Navegación principal de administración',
    tabs: {
      applicants: 'Postulantes',
      merchants: 'Comercios',
      incidents: 'Incidentes',
      settings: 'Parámetros',
      audit: 'Auditoría',
    },
  },
  applicantStatus: {
    pending: 'Pendiente',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    suspended: 'Suspendido',
  },
  documentStatus: {
    none: 'Sin cargar',
    submitted: 'Pendiente',
    verified: 'Verificado',
    rejected: 'Rechazado',
  },
  vehicleType: {
    walk: 'A pie',
    bike: 'Bicicleta',
    moto: 'Moto',
    car: 'Automóvil',
  },
  documentKind: {
    dni_front: 'DNI Frente',
    dni_back: 'DNI Dorso',
    selfie: 'Selfie con DNI',
    avatar: 'Foto de Perfil',
    license: 'Licencia de Conducir',
    insurance: 'Seguro de Vehículo',
  },
  queue: {
    title: 'Postulantes',
    description:
      'Bandeja de verificación de documentación y aprobación de repartidores en Aguilares.',
    tabs: {
      pending: 'Pendientes',
      approved: 'Aprobados',
      rejected: 'Rechazados',
      suspended: 'Suspendidos',
    },
    columns: {
      applicant: 'Postulante',
      vehicle: 'Vehículo',
      documents: 'Documentación',
      level: 'Nivel',
      date: 'Fecha',
      action: 'Acción',
    },
    dniHashLabel: 'DNI Hash',
    dniBadge: 'DNI',
    selfieBadge: 'Selfie',
    licenseBadge: 'Licencia',
    insuranceBadge: 'Seguro',
    uploadedFeminine: 'subida',
    uploadedMasculine: 'subido',
    level: (value: number) => `Nivel ${value}`,
    emptyTitle: (tabLabel: string) => `No hay postulantes en estado "${tabLabel}"`,
    emptyDescription:
      'Cuando un repartidor complete su registro o cambie de estado, aparecerá en esta lista.',
    nextButton: 'Siguiente',
    reviewButton: 'Revisar',
  },
  detail: {
    backToList: '← Volver a la lista de postulantes',
    labels: {
      dniHash: 'DNI Hash',
      phone: 'Teléfono',
      vehicle: 'Vehículo',
      level: 'Nivel',
      state: 'Estado',
      uploadedAt: 'Subido el',
    },
    applicantActions: {
      reject: 'Rechazar postulación',
      approve: 'Aprobar repartidor',
      suspend: 'Suspender repartidor',
      reactivate: 'Reactivar repartidor',
      reconsider: 'Reconsiderar aprobación',
    },
    auditBannerTitle: 'Acceso Auditado y Restringido:',
    auditBannerText:
      'El acceso a estos documentos queda registrado en la auditoría inmutable. Las imágenes se sirven exclusivamente mediante URLs temporales de 60 segundos desde almacenamiento privado cifrado.',
    documentationTitle: (count: number) => `Documentación (${count})`,
    documentationDescription: 'Seleccioná un archivo para revisarlo.',
    documentsAriaLabel: 'Documentos del postulante',
    emptyDocuments: 'No hay documentos registrados para este postulante.',
    loadDocument: 'Cargar documento seguro (60s)',
    loadingDocument: 'Generando acceso seguro...',
    verifyDocument: 'Verificar documento',
    verifyingDocument: 'Verificando...',
    rejectDocument: 'Rechazar documento',
    viewer: {
      zoomOut: 'Reducir zoom',
      zoomIn: 'Aumentar zoom',
      rotate: 'Rotar 90 grados',
      rotateTitle: 'Rotar 90°',
      reset: 'Restablecer vista',
      resetButton: 'Reset',
      expiry: (seconds: number) => `URL temporal expira en: ${seconds}s`,
      protectedTitle: 'Documento protegido',
      protectedDescription:
        'Hacé clic para generar un enlace temporal firmado de 60 segundos y registrar el evento en auditoría.',
      validityQuestion: '¿El documento es legible y válido?',
      imageAlt: (label: string) => `Documento ${label}`,
    },
    rejectDialogTitle: 'Rechazar comprobante',
    rejectDialogDescription: (docLabel: string) =>
      `Ingresá el motivo específico por el cual se rechaza el documento ${docLabel}. Este motivo será notificado al postulante.`,
    rejectDialogReasonLabel: 'Motivo del rechazo',
    rejectDialogReasonPlaceholder:
      'Ej: La imagen del DNI está borrosa y no se distinguen los números.',
    rejectDialogConfirm: 'Confirmar rechazo',
    rejectDialogCanceling: 'Rechazando...',
    decisionDialogTitle: (decision: string | null) =>
      decision === 'approved'
        ? 'Aprobar repartidor'
        : decision === 'rejected'
        ? 'Rechazar postulación'
        : decision === 'suspended'
        ? 'Suspender repartidor'
        : 'Decisión sobre postulante',
    decisionDialogDescription:
      'Para garantizar la transparencia operativa, debés ingresar el motivo vinculante que quedará registrado en el historial.',
    decisionDialogReasonLabel: 'Motivo de la decisión',
    decisionPlaceholder: (decision: string | null) =>
      decision === 'approved'
        ? 'Ej: Documentación DNI y selfie verificada. Cumple con los requisitos del piloto.'
        : decision === 'rejected'
        ? 'Ej: Documento DNI ilegible o vencido.'
        : 'Ej: Reclamo reiterado de comercios por demora injustificada.',
    decisionDialogConfirm: 'Confirmar decisión',
    decisionDialogProcessing: 'Procesando...',
    cancelButton: 'Cancelar',
    success: {
      documentLoaded: 'Documento cargado bajo sesión auditada.',
      documentVerified: 'Documento verificado correctamente.',
      documentRejected: 'Documento marcado como rechazado.',
      courierSuspended: 'Repartidor suspendido con éxito.',
      applicantApproved: 'Postulante aprobado como repartidor activo.',
      applicantRejected: 'Postulación rechazada.',
    },
    errors: {
      loadDocumentConnection: 'Error de conexión al solicitar visualización del documento.',
      verifyDocumentConnection: 'Error de conexión al verificar documento.',
      decisionConnection: 'Error de conexión al procesar la decisión.',
    },
  },
  mfa: {
    title: 'Verificación en dos pasos',
    description:
      'Ingresá el código de 6 dígitos generado por tu app autenticadora (Google Authenticator, Authy, etc.).',
    codeLabel: 'Código de seguridad',
    countdown: (seconds: number) =>
      `Expira en 00:${String(seconds).padStart(2, '0')}`,
    invalidCode: 'Código incorrecto o expirado. Verificá tu app e intentá de nuevo.',
    connectionError: 'Error de conexión al verificar el segundo factor.',
    success: 'Identidad verificada con éxito.',
    validationFallback: 'Ingresá los 6 dígitos numéricos.',
    verifyButton: 'Verificar código',
    verifyingButton: 'Verificando...',
    troubleshoot:
      '¿Problemas con el código de tu app autenticadora? Asegurate de que la hora de tu dispositivo esté sincronizada automáticamente.',
  },
  merchants: {
    title: 'Comercios',
    description: 'Plan y vigencia de los comercios adheridos en Aguilares.',
    tableLabel: 'Comercios adheridos',
    columns: {
      business: 'Comercio',
      owner: 'Responsable',
      phone: 'Teléfono',
      zone: 'Barrio',
      plan: 'Plan',
      paidUntil: 'Pagado hasta',
      delivered: 'Despachos',
      actions: 'Acciones',
    },
    status: {
      pilot: 'Piloto',
      active: 'Activo',
      expired: 'Vencido',
      cancelled: 'Cancelado',
    },
    empty: '—',
    emptyTitle: 'No hay comercios adheridos',
    emptyDescription: 'Cuando un comercio de Aguilares se registre, va a aparecer acá.',
    editPlan: 'Editar plan',
    editPlanFor: (businessName: string) => `de ${businessName}`,
    nextButton: 'Siguiente',
    firstPage: 'Volver al inicio',
    paginationLabel: 'Paginación de comercios',
    dialog: {
      title: (businessName: string) => `Editar plan de ${businessName}`,
      description: 'Elegí qué querés registrar. El cambio queda en la auditoría.',
      modeLabel: 'Tipo de cambio',
      modes: {
        paid: 'Marcar mes pagado',
        pilot: 'Extender piloto',
      },
      modeHelp: {
        paid: 'Activa el plan del comercio hasta la fecha indicada.',
        pilot: 'Mantiene al comercio en piloto hasta la fecha indicada.',
      },
      dateLabel: {
        paid: 'Pagado hasta',
        pilot: 'Piloto hasta',
      },
      paymentNote: 'cadeApp no registra montos ni comprobantes de pago.',
      cancel: 'Cancelar',
      save: 'Guardar',
      saving: 'Guardando...',
    },
    success: 'Plan actualizado.',
    connectionError: 'Error de conexión al actualizar el plan.',
  },
  settings: {
    title: 'Parámetros',
    description: 'Configuración operativa de cadeApp en Aguilares.',
    warningTitle: 'Atención',
    warning:
      'Los cambios aplican al instante para todos y quedan registrados en la auditoría. Modificá los valores con responsabilidad.',
    save: 'Guardar',
    saving: 'Guardando...',
    fields: {
      min_offer_ars: {
        label: 'Oferta mínima',
        help: 'Las ofertas por debajo de este monto se rechazan.',
        unit: '$',
        unitLabel: 'en pesos',
      },
      request_ttl_minutes: {
        label: 'Vencimiento de solicitudes',
        help: 'Tiempo que una solicitud publicada espera ofertas.',
        unit: 'min',
        unitLabel: 'en minutos',
      },
      pilot_active: {
        label: 'Piloto activo',
        help: 'Mientras está activo, los comercios en piloto publican sin pagar el plan.',
        unit: '',
        unitLabel: '',
      },
      pilot_terms_version: {
        label: 'Versión de términos del piloto',
        help: 'Cambiarla obliga a volver a aceptar los términos del piloto.',
        unit: '',
        unitLabel: '',
      },
      subscription_grace_days: {
        label: 'Días de gracia del plan',
        help: 'Días posteriores al vencimiento del plan antes de bloquear nuevas solicitudes.',
        unit: 'días',
        unitLabel: 'en días',
      },
    },
    pilotOn: 'Encendido',
    pilotOff: 'Apagado',
    success: 'Parámetro actualizado.',
    connectionError: 'Error de conexión al guardar el parámetro.',
  },
  recentChanges: {
    title: 'Últimos cambios',
    empty: 'Sin cambios recientes.',
    viewAll: 'Ver registro completo en Auditoría',
  },
  audit: {
    title: 'Auditoría',
    description: 'Registro de acciones administrativas y cambios de estado.',
    readOnlyBadge: 'Solo lectura',
    tableLabel: 'Registro de auditoría',
    system: 'Sistema',
    unnamedOperator: 'Operador sin nombre',
    filters: {
      label: 'Filtros de auditoría',
      actor: 'Operador',
      allActors: 'Todos los operadores',
      action: 'Tipo de evento',
      allActions: 'Todos los eventos',
      entity: 'Entidad',
      allEntities: 'Todas las entidades',
      apply: 'Filtrar',
      clear: 'Limpiar filtros',
    },
    columns: {
      date: 'Fecha y hora',
      operator: 'Operador',
      action: 'Acción',
      entity: 'Entidad',
      detail: 'Detalle',
    },
    actions: {
      admin_set_subscription: 'Cambió el plan',
      admin_update_setting: 'Cambió un parámetro',
      admin_decide_courier: 'Decidió una postulación',
      admin_suspend_courier: 'Suspendió un repartidor',
      admin_verify_document: 'Revisó un documento',
      view_courier_document: 'Vio un documento',
      publish_request: 'Publicó una solicitud',
      republish_request: 'Republicó una solicitud',
      cancel_request: 'Canceló una solicitud',
      mark_picked_up: 'Marcó el retiro',
      mark_delivered: 'Marcó la entrega',
      report_no_show: 'Reportó una ausencia',
      courier_cancel_match: 'El repartidor canceló',
    },
    unknownAction: 'Otro evento',
    entities: {
      courier: 'Repartidor',
      courier_document: 'Documento',
      merchant: 'Comercio',
      platform_setting: 'Parámetro',
      delivery_request: 'Solicitud',
    },
    unknownEntity: 'Otra entidad',
    fields: {
      status: 'Estado',
      subscription_status: 'Plan',
      paid_until: 'Pagado hasta',
      value: 'Valor',
      kind: 'Documento',
      docLevel: 'Nivel',
      withdrawnOffersCount: 'Ofertas retiradas',
    },
    values: {
      pending: 'Pendiente',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      suspended: 'Suspendido',
      none: 'Sin cargar',
      submitted: 'Enviado',
      verified: 'Verificado',
      pilot: 'Piloto',
      active: 'Activo',
      expired: 'Vencido',
      cancelled: 'Cancelado',
      draft: 'Borrador',
      published: 'Publicada',
      matched: 'Asignada',
      in_transit: 'En viaje',
      delivered: 'Entregada',
    },
    noValue: '—',
    withReason: 'Con motivo registrado',
    noChanges: 'Sin cambios de estado',
    nextButton: 'Siguiente',
    firstPage: 'Volver al inicio',
    paginationLabel: 'Paginación de la auditoría',
    emptyTitle: 'No hay registros para mostrar',
    emptyDescription: 'Probá con otros filtros o volvé más tarde.',
  },
  errors: {
    merchants: {
      title: 'No pudimos cargar los comercios',
      description: 'Ocurrió un inconveniente al consultar los comercios adheridos.',
      retry: 'Reintentar',
    },
    settings: {
      title: 'No pudimos cargar los parámetros',
      description: 'Ocurrió un inconveniente al consultar la configuración de la plataforma.',
      retry: 'Reintentar',
    },
    audit: {
      title: 'No pudimos cargar la auditoría',
      description: 'Ocurrió un inconveniente al consultar el registro de auditoría.',
      retry: 'Reintentar',
    },
    queue: {
      title: 'No pudimos cargar la cola de postulantes',
      description: 'Ocurrió un inconveniente al consultar los datos de repartidores.',
      retry: 'Reintentar',
    },
    detail: {
      title: 'No pudimos cargar el detalle del postulante',
      description: 'Ocurrió un inconveniente al consultar la documentación del repartidor.',
      retry: 'Reintentar',
      back: 'Volver a la cola',
    },
  },
} as const;
