export const authCopy = {
  login: {
    title: 'Ingresá a tu cuenta',
    subtitle: 'Logística directa para comercios y repartidores de Aguilares',
    emailLabel: 'Email',
    emailPlaceholder: 'tu@email.com',
    passwordLabel: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    submitButton: 'Ingresar',
    loadingButton: 'Ingresando...',
    noAccount: '¿No tenés cuenta?',
    registerLink: 'Registrate',
    errorInvalidCredentials: 'Email o contraseña incorrectos.',
    errorGeneric: 'Ocurrió un error al intentar ingresar. Por favor, reintentá.',
    showPassword: 'Ver contraseña',
    hidePassword: 'Ocultar contraseña',
  },
  register: {
    title: '¿Cómo vas a usar cadeApp?',
    merchantRoleTitle: 'Tengo un comercio o emprendimiento',
    merchantRoleDesc: 'Publicá entregas y elegí al repartidor.',
    courierRoleTitle: 'Quiero repartir',
    courierRoleDesc: 'Ofertá en las entregas de tu ciudad.',
    emailLabel: 'Email',
    emailPlaceholder: 'tu@email.com',
    passwordLabel: 'Contraseña',
    passwordHelper: 'Mínimo 8 caracteres',
    termsAccept: 'Acepto los Términos y la Política de privacidad',
    submitButton: 'Crear cuenta',
    loadingButton: 'Creando cuenta...',
    hasAccount: '¿Ya tenés cuenta?',
    loginLink: 'Ingresá',
    errorGeneric:
      'No pudimos completar el registro con esos datos. Revisá que el email esté bien escrito, elegí una contraseña más segura y evitá las demasiado comunes. Si ya tenés una cuenta, probá ingresar o recuperar tu contraseña.',
    errorRateLimited: 'Hiciste muchos intentos seguidos. Esperá unos minutos y volvé a probar.',
    errorUnexpected: 'Tuvimos un problema al crear tu cuenta. Probá de nuevo en unos minutos.',
    errorAdminRejected: 'El rol solicitado no es válido para el registro público.',
    errorTermsRequired: 'Tenés que aceptar los Términos y la Política de privacidad.',
  },
  forgotPassword: {
    title: 'Recuperá tu contraseña',
    subtitle: 'Ingresá tu email y te mandamos las instrucciones para volver a entrar.',
    emailLabel: 'Email',
    emailPlaceholder: 'tu@email.com',
    submitButton: 'Enviar instrucciones',
    loadingButton: 'Enviando...',
    backToLogin: 'Volver al ingreso',
    successMessage:
      'Si el email coincide con una cuenta registrada, te enviamos las instrucciones para restablecer tu contraseña. Revisá tu casilla de correo.',
  },
} as const;
